# FastAPI application entry point. Run with:
#   uvicorn app.main:app --reload
# Swagger UI lives at /docs, ReDoc at /redoc (both auto-generated by FastAPI).
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.v1.router import router as v1_router
from app.core.config import settings

app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    docs_url="/docs",
    redoc_url="/redoc",
)

# Which frontend URLs are allowed to call this API — read from settings
# (ALLOWED_ORIGINS env var) instead of hardcoded, so pointing this API at a
# deployed frontend later is a config change, not a code change.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(v1_router, prefix="/api/v1")


# Root route — a friendly landing message if you hit the API directly.
@app.get("/")
async def root():
    return {"message": "DevPulse API is running", "docs": "/docs"}
